[workspace]
members = [".", "ui"]

[package]
name = "windows-update-manager"
version = "0.2.3"
edition = "2024"
authors = ["Sovereign"]

[lib]
name = "wum"
path = "src/lib.rs"

[[bin]]
name = "windows-update-manager"
path = "src/main.rs"

[dependencies]
colored = "3.0.0"
crossterm = "0.29.0"
tui = "0.19.0"
windows = { version = "0.61.3", features = [
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_System_Threading",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_System_Registry",
    "Win32_System_Services",
    "Win32_System_Com",
    "Win32_System_TaskScheduler",
    "Win32_System_Variant",
    "Win32_System_Ole",
    "Win32_UI_Shell",
] }
winreg = "0.55.0"
open = "5.3.2"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
strip = true
panic = "abort"
